name: Brew Update Package
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install venv
      run: |
        python3 -m venv venv
    - name: Activate the newly created virtual environment
      run: |
        source venv/bin/activate
        pip install aws-google-saml homebrew-pypi-poet
        poet --formula aws-google-saml > Formula/aws-google-saml.rb
        deactivate
    - name: Replace python3 with python
      run: |
        sed -i 's/virtualenv_create(libexec, "python3")//g' aws-google-saml.rb
        sed -i 's/Shiny new formula/A user browser driven SAML authentication tool for AWS/g' aws-google-saml.rb
    - name: Commit report
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git add Formula/aws-google-saml.rb
        git commit -am "Automated report"
        git push
